tunnel: 503759d7-854c-44a6-ae83-c63c3260c13a
credentials-file: C:\Users\zzkid\.cloudflared\503759d7-854c-44a6-ae83-c63c3260c13a.json

ingress:
  - hostname: godbrain.org
    service: http://127.0.0.1:8000
  - hostname: www.godbrain.org
    service: http://127.0.0.1:8000
  - hostname: app.godbrain.org
    service: http://127.0.0.1:3000
  - hostname: api.godbrain.org
    service: http://127.0.0.1:8001
  - service: http_status:404
